apiVersion: apps/v1
kind: Deployment
metadata:
  name: echotest
  labels:
    app: echotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echotest
  template:
    metadata:
      labels:
        app: echotest
    spec:
      containers:
      - name: test
        image: 616496521288.dkr.ecr.us-east-2.amazonaws.com/tworptest:latest
        env:
        - name: TWORPTEST
          valueFrom:
            secretKeyRef:
              name: secret-echo-test
              key: super_secret
#     imagePullSecrets:
#       name: awsecr-cred
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-echo-test
type: Opaque
data:
  super_secret: dHJ1ZTEwMCU=
