apiVersion: apps/v1
kind: Deployment
metadata:
  name: echotest
  labels:
    app: echotest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echotest
  template:
    metadata:
      labels:
        app: echotest
    spec:
      containers:
      - name: test
        image: matheusbasilio/tworptest:latest
        ports:
        - containerPort: 80
        env:
          - name: TWORPTEST
            value: "true100%"
---
apiVersion: v1
kind: Service
metadata:
  name: service-echo
spec:
  selector:
    app: echotest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
---